export const sellerCardInfo = [
  {
    serial: "01",
    image: "/images/profilemask.svg",
    verifyTick: "/images/tickmark.svg",
    name: "@yukanne",
    balance: "$6,486,658",
    borderColor: "#FCB808",
  },
  {
    serial: "02",
    image: "/images/profilemask.svg",
    verifyTick: "/images/tickmark.svg",
    name: "@yukanne",
    balance: "$6,486,658",
    borderColor: "#FCB808",
  },
  {
    serial: "03",
    image: "/images/profilemask.svg",
    verifyTick: "/images/tickmark.svg",
    name: "@yukanne",
    balance: "$6,486,658",
    borderColor: "#FCB808",
  },
  {
    serial: "04",
    image: "/images/profilemask.svg",
    verifyTick: "/images/tickmark.svg",
    name: "@yukanne",
    balance: "$6,486,658",
    borderColor: "#FCB808",
  },
  {
    serial: "05",
    image: "/images/profilemask.svg",
    verifyTick: "/images/tickmark.svg",
    name: "@yukanne",
    balance: "$6,486,658",
    borderColor: "#FCB808",
  },
  {
    serial: "06",
    image: "/images/profilemask.svg",
    verifyTick: "/images/tickmark.svg",
    name: "@yukanne",
    balance: "$6,486,658",
    borderColor: "#FCB808",
  },
  {
    serial: "07",
    image: "/images/profilemask.svg",
    verifyTick: "/images/tickmark.svg",
    name: "@yukanne",
    balance: "$6,486,658",
    borderColor: "#FCB808",
  },
  {
    serial: "08",
    image: "/images/profilemask.svg",
    verifyTick: "/images/tickmark.svg",
    name: "@yukanne",
    balance: "$6,486,658",
    borderColor: "#FCB808",
  },
  {
    serial: "09",
    image: "/images/profilemask.svg",
    verifyTick: "/images/tickmark.svg",
    name: "@yukanne",
    balance: "$6,486,658",
    borderColor: "#FCB808",
  },
  {
    serial: "10",
    image: "/images/profilemask.svg",
    verifyTick: "/images/tickmark.svg",
    name: "@yukanne",
    balance: "$6,486,658",
    borderColor: "#FCB808",
  },
  {
    serial: "11",
    image: "/images/profilemask.svg",
    verifyTick: "/images/tickmark.svg",
    name: "@yukanne",
    balance: "$6,486,658",
    borderColor: "#FCB808",
  },
  {
    serial: "12",
    image: "/images/profilemask.svg",
    verifyTick: "/images/tickmark.svg",
    name: "@yukanne",
    balance: "$6,486,658",
    borderColor: "#FCB808",
  },
  {
    serial: "13",
    image: "/images/profilemask.svg",
    verifyTick: "/images/tickmark.svg",
    name: "@yukanne",
    balance: "$6,486,658",
    borderColor: "#FCB808",
  },
  {
    serial: "14",
    image: "/images/profilemask.svg",
    verifyTick: "/images/tickmark.svg",
    name: "@yukanne",
    balance: "$6,486,658",
    borderColor: "#FCB808",
  },
  {
    serial: "15",
    image: "/images/profilemask.svg",
    verifyTick: "/images/tickmark.svg",
    name: "@yukanne",
    balance: "$6,486,658",
    borderColor: "#FCB808",
  },
];

export const categoryInfo = [
  {
    image1: "/images/categoryDemo1.svg",
    image2: "/images/categoryDemo2.svg",
    image3: "/images/categoryDemo3.svg",
    name: "Famous Race Cars 🎨 ",
  },
  {
    image1: "/images/categoryDemo1.svg",
    image2: "/images/categoryDemo2.svg",
    image3: "/images/categoryDemo3.svg",
    name: "F1 Heroes ✨",
  },
  {
    image1: "/images/categoryDemo1.svg",
    image2: "/images/categoryDemo2.svg",
    image3: "/images/categoryDemo3.svg",
    name: "F1 Music 🎵",
  },
  {
    image1: "/images/categoryDemo1.svg",
    image2: "/images/categoryDemo2.svg",
    image3: "/images/categoryDemo3.svg",
    name: "F1 Photography 📸",
  },
  {
    image1: "/images/categoryDemo1.svg",
    image2: "/images/categoryDemo2.svg",
    image3: "/images/categoryDemo3.svg",
    name: "F1 Metaverse",
  },
  {
    image1: "/images/categoryDemo1.svg",
    image2: "/images/categoryDemo2.svg",
    image3: "/images/categoryDemo3.svg",
    name: "F1 Metaverse",
  },
];
